hmac_secret: "my$ecretK3y"

# Mounted filesystems
filesystems:
  transfer: tmp/transfer

s3:
  access_key_id: minio-user
  secret_access_key: minio-password
  bucket: stacks-test
  endpoint: http://localhost:9000
